---
author: "Ciaran Evans"
title: Maximum likelihood estimation
output:
  xaringan::moon_reader:
    css: "lab-slides.css"
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
editor_options: 
  chunk_output_type: console
---

### Logistics and reminders

.large[
* HW 1 due tonight
* Reminder: bank of 5 extension days -- can use 1 or 2 days on a homework assignment or project piece
* HW 2 released, due next Friday
* Project part 1 released (choosing a dataset + EDA)
    * Project will be released in several pieces
    * Part 1 due in 2 weeks
* Coming up:
    * Logistic regression assumptions and diagnostics
    * Inference (hypothesis tests, confidence intervals)
]

---

### Warmup: maximum likelihood estimation

.large[
Work on the activity (handout), then we will discuss as a course
]

---

### Warmup

.large[
Independent observations $Y_1,...,Y_n$ with $P(Y_i|\pi) = (1 - \pi)^{Y_i - 1} \pi$.

Likelihood function:

$$L(\pi) = P(Y_1|\pi)P(Y_2|\pi) \cdots P(Y_n|\pi) = \prod \limits_{i=1}^n P(Y_i | \pi)$$
]

---

### Warmup

.large[
$$L(\pi) = (1 - \pi)^{\sum \limits_{i=1}^nY_i - n}\pi^n$$
]

---

### MLE for logistic regression

.large[
Suppose we observe independent samples $(X_1, Y_1),...,(X_n, Y_n)$ with
$$Y_i \sim Bernoulli(\pi_i) \hspace{1cm} \log \left( \dfrac{\pi_i}{1 - \pi_i} \right) = \beta_0 + \beta_1 X_i$$
**Likelihood:**
]

---

### Class activity, Part 2

.large[
Maximizing likelihood for a logistic regression model in R (linked on class website):

[https://sta214-f26.github.io/class_activities/ca_06_2.html](https://sta214-f26.github.io/class_activities/ca_06_2.html)

(You do not need to submit this part of the activity)
]


