---
title: "Class activity: maximum likelihood estimation"
format: pdf
editor: source
---

\vspace{-2.5cm}

**Group members:**

**Instructions:** Work with a neighbor on the following activity. I will collect the handout at the end of class, and it will be part of your class participation grade. You will be graded only on effort -- it is ok if you don't finish all the questions, or get them all correct.

## Maximum likelihood estimation

Suppose we have a variable $Y$ that can take **three** possible outcomes: $Y = -1, 0$, or $1$. We also know that

* $P(Y_i = 0) = \pi_0$
* $P(Y_i = -1) = 2 \pi_0$
* $P(Y_i = 1) = 1 - 3 \pi_0$

where the parameter $\pi_0$ is unknown. We observe (independent) data $-1, -1, 0, 1, 0, -1$, and we want to estimate $\pi_0$ from the data.

# Questions


1. Write down the likelihood $L(\pi_0)$ for the observed data $-1, -1, 0, 1, 0, -1$.

\vspace{3cm}

2. Use calculus to maximize the likelihood from Exercise 1. Remember to differentiate the log likelihood, and recall the following rules for logs and derivatives:

* $\log(xy) = \log(x) + \log(y)$
* $\log(x^y) = y \log(x)$
* $\dfrac{d}{dx} \log x = \dfrac{1}{x}$
* $\dfrac{d}{dx} c f(x) = c \dfrac{d}{dx} f(x)$ for constant $c$
* $\dfrac{d}{dx} (f(x) + c) = \dfrac{d}{dx} f(x)$ for constant $c$
* $\dfrac{d}{dx} (f(x) + g(x)) = \dfrac{d}{dx} f(x) + \dfrac{d}{dx} g(x)$

