---
title: "Activity"
format: pdf
editor: source
---

\vspace{-2.5cm}

**Group members:**

# BRFSS data: weight loss and exercise

The Behavioral Risk Factor Surveillance System (BRFSS) is an annual telephone survey of 350,000 people in the United States. As its name implies, the BRFSS is designed to identify risk factors in the adult population and report emerging health trends. For example, respondents are asked about their diet and weekly physical activity, possible tobacco use, and even their level of healthcare coverage.

We will focus on a random sample of 20,000 people from the BRFSS survey. This sample includes information on the following variables:

* `exerany`: indicates whether the respondent exercised in the past month (1) or did not (0).
* `loss`: the proportion of body weight which the respondent wants to lose
* `smoke100`: indicates whether the respondent had smoked at least 100 cigarettes in their lifetime
* `hltplan`: indicates whether the respondent had some form of health coverage (1) or did not (0).
* `age`: in years
* `height`: in inches

**Research question:** After accounting for the respondent's desired weight loss, is there any relationship between the other explanatory variables and exercise?

## Model

A collaborator fits the following regression model with `exerany` as the response:

$$
\begin{aligned}
\text{Exercise}_i &\sim Bernoulli(\pi_i) \\
\log \left( \dfrac{\pi_i}{1 - \pi_i} \right) &= \beta_0 + \beta_1 \text{Loss}_i + \beta_2 \text{Smoke}_i + \beta_3 \text{HealthPlan}_i + \beta_4 \text{Age}_i + \beta_5 \text{Height}_i
\end{aligned}
$$

## Questions

1. Write down the null and alternative hypotheses corresponding to the research question.

\vspace{3cm}

2. Write down the reduced model.

\vspace{3cm}

3. Below is output for the fitted models. Calculate an appropriate test statistic to test the hypotheses in question 1. What will be the degrees of freedom for the $\chi^2$ distribution under $H_0$?

(*Note:* R reports deviance for the fitted model as the *residual deviance*)

```{r, eval=F, include=F}
source("http://www.openintro.org/stat/data/cdc.R")
cdc <- cdc |>
  mutate(loss = (weight - wtdesire)/weight)
m1 <- glm(exerany ~ loss + smoke100 + hlthplan + age + height,
          data = cdc, family = binomial)
summary(m1)

m2 <- glm(exerany ~ loss,
          data = cdc, family = binomial)
summary(m2)
```

**Model 1:**

```
glm(formula = exerany ~ loss + smoke100 + hlthplan + age + height, 
    family = binomial, data = cdc)

Coefficients:
              Estimate Std. Error z value Pr(>|z|)    
(Intercept) -2.0928484  0.2890071  -7.242 4.44e-13 ***
loss        -1.4520863  0.1500420  -9.678  < 2e-16 ***
smoke100    -0.1339504  0.0334117  -4.009 6.10e-05 ***
hlthplan     0.5940486  0.0478039  12.427  < 2e-16 ***
age         -0.0129321  0.0009882 -13.086  < 2e-16 ***
height       0.0512637  0.0041823  12.257  < 2e-16 ***
---

    Null deviance: 22680  on 19999  degrees of freedom
Residual deviance: 22036  on 19994  degrees of freedom
```

\newpage

**Model 2:**

```
Coefficients:
            Estimate Std. Error z value Pr(>|z|)    
(Intercept)  1.21576    0.02036   59.72   <2e-16 ***
loss        -1.78208    0.14609  -12.20   <2e-16 ***
---

    Null deviance: 22680  on 19999  degrees of freedom
Residual deviance: 22531  on 19998  degrees of freedom
```




