---
title: "Activity"
format: 
  pdf:
    header-includes:
      - \usepackage{float}
      - \floatplacement{table}{H}
editor: source
---

\vspace{-2.5cm}

# Core temperature and post-surgery infections

When patients undergo surgery, the anesthesia received can lower their core temperature. While surgical environments are controlled and aim to regulate patient core temperature, some degree of cooling can still occur. *Hypothermia* during surgery is said to occur if the core temperature is below $36^\circ\text{C}$, and we might suspect that greater differences from $36^\circ\text{C}$ would be associated with worse outcomes. Furthermore, it is possible that there is a relationship between core temperature and patient outcomes even within the normal range of body temperatures ($36 - 37.5^\circ\text{C}$).

Walters *et al.* (2020) conducted a study to investigate the relationship between core temperature and the risk of serious infection in colorectal surgery patients. Their study included 7908 adult patients who received colorectal surgery between January 2005 and December 2014, and who had general anesthesia for a surgery lasting at least one hour that included at least 30 minutes of esophageal core temperature monitoring (see Walters *et al.* for the full inclusion/exclusion criteria). The study authors then recorded whether each patient developed a serious infection within 30 days after surgery.

**Research question:** What is the relationship between core temperature during surgery, and the risk of developing a serious infection after surgery?

# Information packet

You have also been provided with a packet that provides information on the data from the study, including:

* A description of each variable
* Summary statistics for the variables
* A number of plots for the available quantitative variables

# Your task

You have been approached by the researchers who conducted this study. They want you to help them plan an analysis, using a regression model to answer their question of interest.

## Questions

1. What is the response variable of interest? What type of variable is this?

\vspace{3cm}

2. There are three different variables included in the data that measure the patient’s core temperature. 
    * Explain how these three variables differ. 
    * Which of these three variables for measuring core temperature would you choose for the analysis? Why?
    
\newpage

3. Which of the available variables in the data could be included as additional explanatory variables in the model? Which variables are *not* suitable choices as explanatory variables? Explain.

\vspace{10cm}


4. Based on your previous responses, propose a preliminary model to address the research question.



