---
title: "Activity"
format: pdf
editor: source
---

\vspace{-2.5cm}

**Group members:**

# BRFSS data: weight loss and exercise

The Behavioral Risk Factor Surveillance System (BRFSS) is an annual telephone survey of 350,000 people in the United States. As its name implies, the BRFSS is designed to identify risk factors in the adult population and report emerging health trends. For example, respondents are asked about their diet and weekly physical activity, their HIV/AIDS status, possible tobacco use, and even their level of healthcare coverage.

We will focus on a random sample of 20,000 people from the BRFSS survey. This sample includes information on the following variables:

* `exerany`: indicates whether the respondent exercised in the past month (1) or did not (0).
* `loss`: the proportion of body weight which the respondent wants to lose
* `smoke100`: indicates whether the respondent had smoked at least 100 cigarettes in their lifetime
* `hltplan`: indicates whether the respondent had some form of health coverage (1) or did not (0).
* `age`: in years
* `height`: in inches

## Model

A collaborator fits the following regression model with `exerany` as the response:

```
Coefficients:
              Estimate Std. Error z value Pr(>|z|)    
(Intercept) -2.0928484  0.2890071  -7.242 4.44e-13 ***
loss        -1.4520863  0.1500420  -9.678  < 2e-16 ***
smoke100    -0.1339504  0.0334117  -4.009 6.10e-05 ***
hlthplan     0.5940486  0.0478039  12.427  < 2e-16 ***
age         -0.0129321  0.0009882 -13.086  < 2e-16 ***
height       0.0512637  0.0041823  12.257  < 2e-16 ***
```

The standard deviation of the `loss` variable is 0.112.

1. How do the odds of exercise change with a one **standard deviation** increase in loss (not a one-unit increase!), holding the other variables constant?

\vspace{3cm}

2. Your collaborators tell you that for the effect of desired weight loss to be clinically meaningful, they would need a one-standard deviation increase in `loss` to be associated with a decrease in the odds of at least 10% (holding other variables constant). Create a confidence interval to address this research question.






