<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Exam 1 review questions</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="exam_1_review_solutions_files/libs/clipboard/clipboard.min.js"></script>
<script src="exam_1_review_solutions_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="exam_1_review_solutions_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="exam_1_review_solutions_files/libs/quarto-html/popper.min.js"></script>
<script src="exam_1_review_solutions_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="exam_1_review_solutions_files/libs/quarto-html/anchor.min.js"></script>
<link href="exam_1_review_solutions_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="exam_1_review_solutions_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="exam_1_review_solutions_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="exam_1_review_solutions_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="exam_1_review_solutions_files/libs/bootstrap/bootstrap-138a6193a3bd40baf1e627da441a4734.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Exam 1 review questions</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="data" class="level2">
<h2 class="anchored" data-anchor-id="data">Data</h2>
<p>Our data today come from the 2015 Gorkha earthquake in Nepal. After the earthquake, a large scale survey was conducted to determine the amount of damage the earthquake caused for homes, businesses and other structures. This is one of the largest post-disaster surveys in the world, and today we will be using it to determine what characteristics were associated building damage.</p>
<p>The data contains information on 10000 buildings, with the following variables:</p>
<ul>
<li><code>age</code>: the age of the building (in years)</li>
<li><code>area_percentage</code>: normalized area of the building footprint</li>
<li><code>height_percentage</code>: normalized height of the building footprint</li>
<li><code>land_surface_condition</code>: a categorical variable recording the surface condition of the land around the building. There are three different levels: n, o, and t. (The researchers who collected the data anonymized the level names to protect inhabitants’ privacy).</li>
<li><code>foundation_type</code>: type of foundation used while building. Possible values: h, i, r, u, w. (The researchers who collected the data anonymized the level names to protect inhabitants’ privacy)</li>
<li><code>roof_type</code>: type of roof used while building. Possible values: n, q, x. (The researchers who collected the data anonymized the level names to protect inhabitants’ privacy)</li>
<li><code>count_families</code>: number of families that live in the building</li>
<li><code>has_secondary_use</code>: whether the building was used for any secondary purpose (0 = no, 1 = yes)</li>
<li><code>Damage</code>: whether the building sustained any damage (1) or not (0)</li>
</ul>
<section id="choosing-and-interpreting-a-model" class="level3">
<h3 class="anchored" data-anchor-id="choosing-and-interpreting-a-model">Choosing and interpreting a model</h3>
<ol type="1">
<li>A collaborator is interested in modeling the probability that a building sustained any damage, based on building age and surface condition. Write down a population regression model that would allow them to explore this research question.</li>
</ol>
<p><strong>Solution:</strong></p>
<p><span class="math display">\[Damage_i \sim Bernoulli(\pi_i)\]</span></p>
<p><span class="math display">\[\log \left( \dfrac{\pi_i}{1 - \pi_i} \right) = \beta_0 + \beta_1 Age_i + \beta_2 SurfaceO_i + \beta_3 SurfaceT_i\]</span></p>
<ol start="2" type="1">
<li>You fit the model for your collaborator in R, producing the following output (<strong>model 1</strong>). Interpret each of the coefficients in the fitted model in terms of the <em>odds</em> of damage.</li>
</ol>
<p><strong>Model 1:</strong></p>
<pre><code>                         Estimate Std. Error 
(Intercept)              1.420845   0.105823  
age                      0.065166   0.003191  
land_surface_conditiono -0.230243   0.205150  
land_surface_conditiont -0.442394   0.105703

    Null deviance: 7250.4  on 9999  degrees of freedom
Residual deviance: 6600.8  on 9996  degrees of freedom</code></pre>
<p><strong>Solution:</strong></p>
<ul>
<li>The estimated odds of damage for a building that is 0 years old, with surface condition N, is <span class="math inline">\(\exp\{1.421\} = 4.141\)</span></li>
<li>A one-year increase in the age of the building is associated with an increase of 6.7% in the odds of damage, holding surface condition constant</li>
<li>Holding age constant, buildings of surface condition O have lower odds of damage than buildings of surface condition N, by 20.5%</li>
<li>Holding age constant, buildings of surface condition T have lower odds of damage than buildings of surface condition N, 35.7%</li>
</ul>
<ol start="3" type="1">
<li>Describe a plot you could use to assess the <em>shape</em> assumption for this model. Make it clear in your description which variables or quantities would be plotted on the graph, and how you would use the plot to assess the shape assumption.</li>
</ol>
<p><strong>Solution:</strong> The shape assumption could be assessed either with an empirical logit plot (before we fit the model), or with a quantile residual plot.</p>
<p>An empirical logit plot groups the observations by binning a numerical explanatory variable, then plots the observed log odds for observations in each bin against the mean of the variable in that bin. A linear relationship suggests that the shape assumption is satisfied, whereas a non-linear relationship suggests we need a transformation.</p>
<p>A quantile residual plot creates a (randomized) quantile residual for each observation in the data, by comparing the predictions from the model against the true observed responses. These residuals can then be plotted against an explanatory variable, or against the fitted values. The plot is interpreted like the usual residual plots from linear regression models: we are looking for a random scatter of the residuals around 0, with no clear patterns.</p>
<ol start="4" type="1">
<li>For the type of plot described in question 3, sketch a hypothetical example plot which suggests that a transformation is needed for an explanatory variable.</li>
</ol>
<p><strong>Solution:</strong> See examples from class</p>
<p><br></p>
<p>(For the remainder of the questions, you may assume that the shape assumption is satisfied for the earthquake data).</p>
<p><br></p>
</section>
<section id="predictions" class="level3">
<h3 class="anchored" data-anchor-id="predictions">Predictions</h3>
<ol start="5" type="1">
<li>Calculate the estimated probability of damage for a 50 year old building with surface condition = t.</li>
</ol>
<p><strong>Solution:</strong> The estimated log odds of damage is</p>
<p><span class="math display">\[1.420845 + 0.065166(50) -0.442394 = 4.237\]</span> and so the estimated probability of damage is</p>
<p><span class="math display">\[\widehat{\pi}_i = \dfrac{e^{4.237}}{1 + e^{4.237}} = 0.986\]</span></p>
<ol start="6" type="1">
<li>Using <strong>model 1</strong>, the predicted probability of damage for a specific building is 0.80. For this building, which observed outcome would result in a higher Cook’s distance: Damage = 0, or Damage = 1?</li>
</ol>
<p><strong>Solution:</strong> Remember that Cook’s distance identifies <em>unusual</em> points – that is, observations that do not follow the trend predicted by the model. If the predicted probability is 0.80, then we would expect Damage = 1. The more unusual observation, and therefore the observation with a higher Cook’s distance, would have Damage = 0.</p>
<ol start="7" type="1">
<li>Below is a confusion matrix for the predictions from the model, created using a threshold of 0.85. Calculate accuracy, sensitivity, specificity, and positive predictive value. How well does the model seem to be predicting?</li>
</ol>
<pre><code>                True Damage
Predicted Damage    0    1
               0  755 2682
               1  423 6140</code></pre>
<p><strong>Solution:</strong></p>
<ul>
<li>Accuracy: (755 + 6140)/10000 = 0.69</li>
<li>Sensitivity: 6140/(6140 + 2682) = 0.70</li>
<li>Specificity: 755/(755 + 423) = 0.641</li>
<li>PPV: 6140/(6140 + 423) = 0.936</li>
</ul>
<p>Overall the model is doing ok at predicting damage (certainly better than random guessing). The accuracy is 69%, which means that 69% of our predictions on the original data are correct. While accuracy is not a very useful measure of performance when classes are imbalanced (as they are here – there are many more Damaged buildings than undamaged buildings), the within-class predictive abilities (sensitivity and specificity) are both similar (70% and 64%, respectively), so we are doing about the same at predicting damaged buildings as undamaged buildings.</p>
<ol start="8" type="1">
<li>Explain how sensitivity and specificity would change if we <em>decreased</em> the threshold used to make the confusion matrix.</li>
</ol>
<p><strong>Solution:</strong> Sensitivity increases (more buildings are classified as “Damaged”), and specificity decreases (fewer buildings are classified as “Undamaged”)</p>
</section>
<section id="inference" class="level3">
<h3 class="anchored" data-anchor-id="inference">Inference</h3>
<ol start="9" type="1">
<li>Using the <strong>R output</strong>, calculate and interpret a 95% confidence interval for the change in odds of damage associated with a one year increase in building age, holding surface condition fixed. The critical value for a 95% confidence interval is <span class="math inline">\(z^* = 1.96\)</span>.</li>
</ol>
<p><strong>Solution:</strong> First, make a 95% confidence interval in terms of a one-year increase and the log-odds:</p>
<p><span class="math display">\[0.0652 \pm 1.96 (0.0032) = (0.059, 0.071)\]</span></p>
<p>Then exponentiate to get the interval in terms of the odds:</p>
<p><span class="math display">\[(e^{0.059}, e^{0.071}) = (1.061, 1.074)\]</span></p>
<p>So: we are 95% confident that a one-year increase in age is associated with an increase in the odds of damage by between 6.1% and 7.4%, holding surface condition constant.</p>
<ol start="10" type="1">
<li>Alternatively, describe how you would use <strong>bootstrap resampling</strong> to compute the 95% confidence interval from the previous question. Explain how you generate a bootstrap sample, what you would calculate for each bootstrap sample, and how you use the bootstrap samples to get the desired confidence interval. You do not need to write code (although you may do so if you wish!), but your explanation should be sufficiently detailed that I could turn it into code.</li>
</ol>
<p><strong>Solution:</strong></p>
<ul>
<li>To generate a bootstrap sample, we resample rows of the original data, with replacement. The bootstrap sample size is the same as the number of rows in the original data.</li>
<li>For each bootstrap sample, we will
<ul>
<li>Refit the model (logistic regression with damage as the response, and age and surface condition as explanatory variables), using the <em>bootstrap</em> sample</li>
<li>Compute the estimated coefficient for building age (<span class="math inline">\(\widehat{\beta}_{age}\)</span>)</li>
</ul></li>
<li>We repeat the process many times (e.g., 10000), generating many bootstrap samples, and so many different coefficient estimates (one for each bootstrap sample)</li>
<li>To compute a 95% confidence interval: <span class="math inline">\(0.0652 \pm 1.96 SE(\widehat{\beta}_{age})\)</span>, where <span class="math inline">\(SE(\widehat{\beta}_{age})\)</span> is the standard deviation of the estimated coefficients from our many bootstrap samples</li>
</ul>
<ol start="11" type="1">
<li>Your collaborator now wants to know whether there is a relationship between surface condition and building damage, after accounting for building age. Write down null and alternative hypotheses, in terms of one or more model parameters, that allow you to address this question.</li>
</ol>
<p><strong>Solution:</strong></p>
<p><span class="math display">\[H_0: \beta_2 = \beta_3 = 0\]</span> <span class="math display">\[H_A: \text{at least one of } \beta_2, \beta_3 \neq 0\]</span></p>
<p><br></p>
<p>To help you test the hypotheses in question 11, below is the output for two other regression models on the same data. You may or may not need to use all of the output provided.</p>
<p><strong>Model 2:</strong></p>
<pre><code>                        Estimate Std. Error 
(Intercept)              2.36548    0.09793  
land_surface_conditiono -0.34877    0.20053  
land_surface_conditiont -0.40014    0.10344 

    Null deviance: 7250.4  on 9999  degrees of freedom
Residual deviance: 7234.1  on 9997  degrees of freedom</code></pre>
<p><strong>Model 3:</strong></p>
<pre><code>            Estimate Std. Error
(Intercept) 1.039066   0.047770   
age         0.065061   0.003191 

    Null deviance: 7250.4  on 9999  degrees of freedom
Residual deviance: 6620.7  on 9998  degrees of freedom</code></pre>
<p><br></p>
<ol start="12" type="1">
<li>Calculate a test statistic that allows you to address the hypotheses in question 11.</li>
</ol>
<p><strong>Solution:</strong> We’re testing multiple coefficients, so we need to use a drop-in-deviance test.</p>
<p><span class="math display">\[G = \text{deviance}_{reduced} - \text{deviance}_{full} = 6620.7 - 6600.8 = 19.9\]</span></p>
<ol start="13" type="1">
<li>Describe how you would use <strong>parametric bootstrapping</strong> to approximate a p-value for the test statistic calculated in question 12. Explain how you would generate a parametric bootstrap sample, what you will calculate for each parametric bootstrap sample, and how you would use the parametric bootstrap samples to test the hypotheses of interest. You do not need to write code (although you may do so if you wish!), but your explanation should be sufficiently detailed that I could turn it into code.</li>
</ol>
<p><strong>Solution:</strong></p>
<ul>
<li>To generate a parametric bootstrap sample, we simulate <em>new</em> response values <span class="math inline">\(\text{Damage}_1^*,...,\text{Damage}_n^*\)</span> using the fitted <strong>reduced</strong> model (<strong>model 3</strong>): <span class="math inline">\(\text{Damage}_i^* \sim Bernoulli(\widehat{\pi}_{i, reduced})\)</span></li>
<li>We then refit both the <strong>full</strong> (model 1) and <strong>reduced</strong> (model 3) models on parametric bootstrap data (simulated responses <span class="math inline">\(\text{Damage}_i^*\)</span>, original values for the explanatory variables)</li>
<li>Using the full and reduced models fit on the parametric bootstrap sample, we compute the change in deviance (deviance of reduced model on simulated data - deviance of full model on simulated data)</li>
<li>Repeat the process many times (e.g., 10000), producing a change-in-deviance statistic for 10000 parametric bootstrap samples</li>
<li>The approximate p-value is the fraction of times that are parametric bootstrap statistics are greater than the original observed statistic (in this example, the original statistic was 19.9)</li>
</ul>
<ol start="14" type="1">
<li>Below is an approximate null distribution for the test statistic, generated from parametric bootstrap sampling. Based on this null distribution, would the test statistic you calculated in question 12 be unusual under the null hypothesis? Explain your reasoning.</li>
</ol>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exam_1_review_solutions_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Solution:</strong> Yes; we can see that a value of 19.9 would be far in the right tail of this null distribution, so it would be very unusual.</p>
</section>
</section>
<section id="maximum-likelihood-practice-question" class="level2">
<h2 class="anchored" data-anchor-id="maximum-likelihood-practice-question">Maximum likelihood practice question</h2>
<p>Suppose we have a random variable <span class="math inline">\(Y\)</span>, and the “probability” function for <span class="math inline">\(Y\)</span> is</p>
<p><span class="math display">\[P(Y = y | \theta) = \theta e^{-\theta y}\]</span></p>
<p>We get <span class="math inline">\(n\)</span> independent observations <span class="math inline">\(Y_1,...,Y_n\)</span> from this distribution, and we want to estimate <span class="math inline">\(\theta\)</span>.</p>
<ol start="15" type="1">
<li>Find the maximum likelihood estimator <span class="math inline">\(\widehat{\theta}\)</span>. Make sure to show all your work.</li>
</ol>
<p><strong>Solution:</strong></p>
<p>Begin by writing down the likelihood function:</p>
<p><span class="math display">\[L(\theta) = \prod \limits_{i=1}^n P(Y_i | \theta) = \prod \limits_{i=1}^n \theta e^{-\theta Y_i} = \theta^n \exp\left\lbrace-\theta\sum \limits_{i=1}^n Y_i\right\rbrace\]</span></p>
<p>Then take the log:</p>
<p><span class="math display">\[\log L(\theta) = n \log(\theta) - \theta\sum \limits_{i=1}^n Y_i\]</span></p>
<p>Differentiating with respect to <span class="math inline">\(\theta\)</span>:</p>
<p><span class="math display">\[\frac{d}{d\theta} \log L(\theta) = \frac{n}{\theta} - \sum \limits_{i=1}^n Y_i \overset{set}{=} 0\]</span></p>
<p>And solving, we get that</p>
<p><span class="math display">\[\theta = \frac{n}{\sum \limits_{i=1}^n Y_i}\]</span></p>
<p>is the value of <span class="math inline">\(\theta\)</span> that maximizes our likelihood. So, our maximum likelihood estimator is</p>
<p><span class="math display">\[\widehat{\theta} = \frac{n}{\sum \limits_{i=1}^n Y_i}\]</span></p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>